name: Build Go Application

on:
  push:
    tags:
      - 'v*' # Trigger only when a tag starting with 'v' is pushed (e.g., v1.0.0)

permissions:
  contents: write

jobs:
  build:
    name: Build Go Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64  # macOS ARM requires cross-compilation tools

    steps:
      - name: Get release version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Change to the required Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Build binaries for multiple platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/app-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/app-linux-arm64 .
          GOOS=darwin GOARCH=arm64 go build -o dist/app-macos-arm64 .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: "Automated release for version ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false
          files: |
            dist/app-linux-amd64
            dist/app-linux-arm64
            dist/app-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}